# Copyright 2022 nicknjihia
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  service-port:
    default:        # TODO Should default port be 80?
    description: |
      The port that is mapped to the remote loadbalancer application's port.
    type: int
